### ISSUE TITLE
Errors installing last version on windows [Commit 82d14a5 Jan 23, 2018]

### ISSUE THREAD

**Issue by alienshop** [goiiot/libmqtt#6]
Hi, so im getting several errors when compiling currently on windows. 

`cannot find package "github.com/goiiot/libmqtt" in any of:...`

`> go get github.com/goiiot/libmqtt`
`# github.com/goiiot/libmqtt`
`...go\src\github.com\goiiot\libmqtt\libmqtt.go:119: syntax error: unexpected = in type declaration`

I fix the entry by removing the = sign on line 119 and then try again:

`> go get github.com/goiiot/libmqtt`
`# github.com/goiiot/libmqtt`
`...go\src\github.com\goiiot\libmqtt\util.go:56: undefined: sync.Map`

Any ideas why its failing at the moment? Did i miss some requirements?

Thanks!

**Comment by alienshop** [comment]
Sorry, this can be closed. Thought i had updated my go version, but was running 1.8, by mistake. Compiles correctly with 1.9.X now.
